[scrolling]
history = 2000
multiplier = 20

[terminal.shell]
#args = ["-l"]
program = "nu"

[window]
decorations = "none"
dynamic_padding = false
startup_mode = "Maximized"

[window.dimensions]
columns = 120
lines = 60

[window.padding]
x = 10
y = 15

[general]
live_config_reload = true

[terminal]
