[scrolling]
history = 2000
multiplier = 20

[terminal]
shell = { program = "nu", args = ["-l"] }

[window]
decorations = "None"
dynamic_padding = false
blur = true
# dimensions = { columns = 120, lines = 40 }

[window.padding]
x = 10
y = 10

[selection]
save_to_clipboard = true

[general]
live_config_reload = true
