# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, modulesPath, inputs, ... }:

{
  imports =
    [
      # Include the default lxd configuration.
      "${modulesPath}/virtualisation/lxc-container.nix"
      # Include the container-specific autogenerated configuration.
      ./incus.nix
      # Include the OrbStack-specific configuration.
      ./orbstack.nix
    ];


  # users.users.langliu = {
  #   uid = 501;
  #   extraGroups = [ "wheel" ];
  #
  #   # simulate isNormalUser, but with an arbitrary UID
  #   isSystemUser = true;
  #   group = "users";
  #   createHome = true;
  #   home = "/home/langliu";
  #   homeMode = "700";
  #   useDefaultShell = true;
  # };
  #
  security.sudo.wheelNeedsPassword = false;

  # This being `true` leads to a few nasty bugs, change at your own risk!
  users.mutableUsers = false;

  time.timeZone = "Asia/Shanghai";

  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  # Extra certificates from OrbStack.
  security.pki.certificates = [
    ''
      -----BEGIN CERTIFICATE-----
MIIDDTCCAfWgAwIBAgIJAL+uEN3PzhCHMA0GCSqGSIb3DQEBCwUAMBQxEjAQBgNV
BAMTCWxvY2FsaG9zdDAeFw0yNDEyMTIwMjUwMjRaFw0yNTEyMTIwMjUwMjRaMBQx
EjAQBgNVBAMTCWxvY2FsaG9zdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
ggEBAOatUbxFs9iS5FFE+KUmcjq1+jIc8AsQ2RTlDmYuBuRctJuR6WBy2APABRel
O48SANlqgzB8ii81C6HyQWu/zN31Osi2Zb7k15m55yLcdYsVFpBimSd1GLJSi3jj
cwjhcakGy+Y40iPy+waMxGEeqAhl6F4mh+xOnoXv1WxAsxBh4Lnj4YhGGFUBt++w
xfBZUxoNmSzqRzgHDajuWB3AfQhL5A+6653N+MB29L9h21xVKbDipQqxPLM4tRDy
fvIlawLT6sI7F/X96dFNfQJsF2wlbfVEwj/8ACTmybeoyOFQ4OqAs2qZA8xfvqd/
ifOzeJDmVvM8xrU+lsbsvwiPCGECAwEAAaNiMGAwDAYDVR0TAQH/BAIwADAOBgNV
HQ8BAf8EBAMCBaAwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwEwFwYDVR0RAQH/BA0w
C4IJbG9jYWxob3N0MA8GCisGAQQBgjdUAQEEAQIwDQYJKoZIhvcNAQELBQADggEB
AM0h44Y2w8K+AmOhkGK6k1WVzcRKY/F71vjlxu7dOMnHY+v9SLIUL5rK27J3KI8N
L81UALOSi/i4K/HhI5Z7KX0z37+Wq2YErdZiHo8qatqLDR+xaVNI+XY2YtbDmP9i
2N/mNyoAiF8uP2iIOK99Ym9AItASeeFl41oRzQSgLFSL74lk7VGYJBJOLyH51UmQ
wuG3kmpXWLT2ecbVbfz1cBCF/zMwF2tGulzmHGseJfeIlYJwQErUVpBgK4uLL0Hc
XmxfDJ5Ru3CkfmXYSu0xkhdwl6iISC1Dsue45bvAgSmrtOtSwy9wYKmrCe21+2P9
pBW7qyVBGUoWDWqi+VM8kiY=
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
MIICDDCCAbOgAwIBAgIRAJgrH9sRYe2LpgFiiLTkVCYwCgYIKoZIzj0EAwIwZjEd
MBsGA1UEChMUT3JiU3RhY2sgRGV2ZWxvcG1lbnQxHjAcBgNVBAsMFUNvbnRhaW5l
cnMgJiBTZXJ2aWNlczElMCMGA1UEAxMcT3JiU3RhY2sgRGV2ZWxvcG1lbnQgUm9v
dCBDQTAeFw0yNDEyMjMwNTAxMTdaFw0zNDEyMjMwNTAxMTdaMGYxHTAbBgNVBAoT
FE9yYlN0YWNrIERldmVsb3BtZW50MR4wHAYDVQQLDBVDb250YWluZXJzICYgU2Vy
dmljZXMxJTAjBgNVBAMTHE9yYlN0YWNrIERldmVsb3BtZW50IFJvb3QgQ0EwWTAT
BgcqhkjOPQIBBggqhkjOPQMBBwNCAAQaOJaY43089+3CutiYHNUftIMZZWPqXhAJ
95XKTDhrzPEpGgjTXecjPECGeURgnjdhMJx9Yz+qswEEpDc5042lo0IwQDAOBgNV
HQ8BAf8EBAMCAQYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUDZm+0Ctrm55Q
VhoReBM8BAGVhAUwCgYIKoZIzj0EAwIDRwAwRAIgQlcetvtIk1B64zNhRv6/JmT3
XeO85ZABSdI5iPTCWC8CIB4xoEvP/YuJBboPy7UK7fOfzdJBhyOnIZUgHsccYi72
-----END CERTIFICATE-----

    ''
  ];

  # This option defines the first version of NixOS you have installed on this particular machine,
  # and is used to maintain compatibility with application data (e.g. databases) created on older NixOS versions.
  #
  # Most users should NEVER change this value after the initial install, for any reason,
  # even if you've upgraded your system to a new NixOS release.
  #
  # This value does NOT affect the Nixpkgs version your packages and OS are pulled from,
  # so changing it will NOT upgrade your system - see https://nixos.org/manual/nixos/stable/#sec-upgrading for how
  # to actually do that.
  #
  # This value being lower than the current NixOS release does NOT mean your system is
  # out of date, out of support, or vulnerable.
  #
  # Do NOT change this value unless you have manually inspected all the changes it would make to your configuration,
  # and migrated your data accordingly.
  #
  # For more information, see `man configuration.nix` or https://nixos.org/manual/nixos/stable/options#opt-system.stateVersion .
  system.stateVersion = "24.11"; # Did you read the comment?
}
